version: "3.9"

services:
  db:
    image: postgres
    container_name: graphql-db
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DBNAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PSQL_USER}", "-d", "${PSQL_DBNAME}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PSQL_HOST: db
      PSQL_USER: ${PSQL_USER}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_DBNAME: ${PSQL_DBNAME}